/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jbboin_myopencvskeleton_CameraPreview */

#ifndef _Included_com_jbboin_myopencvskeleton_CameraPreview
#define _Included_com_jbboin_myopencvskeleton_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jbboin_myopencvskeleton_CameraPreview
 * Method:    ImageProcessing
 * Signature: (II[B[I)V
 */
JNIEXPORT void JNICALL Java_com_jbboin_myopencvskeleton_CameraPreview_ImageProcessing
  (JNIEnv *, jobject, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
